version: '3.9'
services:
  database:
    image: postgres:12.16-bullseye
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - postgres_network
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - ./db/batch-clean-up.sh:/batch-cleanup-script.sh

networks:
  postgres_network: